### ISSUE TITLE
[CT-1] 초기 개발환경 셋업 - 4h

### ISSUE THREAD

**Issue by nosorae** [f-lab-edu/chart-trainer#1]
## Todo
- [x] 프로젝트 생성 및 깃허브 연동, gitignore 추가 (0.5h)
- [x] data, domain, presentation 모듈 생성 및 의존 관계 설정 (0.5h)
- [x] Hilt 의존성 추가 및 초기화(1h)
- [ ] Ktlint 의존성 추가 및 PR Github Action 에 린트검사 추가 (1h)
- [x] buildSrc 추가 및 적용, 불필요 의존성 제거 (1h)
