### ISSUE TITLE
[CT-12] 레이어별 모듈 세분화

### ISSUE THREAD

**Issue by nosorae** [f-lab-edu/chart-trainer#12]
## 목적
- 모듈을 나눠 필요한 것에만 의존하게 만든다.
- 책임을 더 작게 나눠 모듈이 비대해지는 것을 막는다.

## TODO 고민중인 것
- [ ]  Presentation과 UI를 분리 ([PR 리뷰 언급](https://github.com/f-lab-edu/chart-trainer/pull/10))
- [ ]  Entity, UseCase, Repository(interface) 분리
- [ ] RepositoryImpl 과 interfaace 분리

## 고려해볼 사항
- [ ] feature 별로 나눌지도 고려해보기
