### ISSUE TITLE
[CT-3] 차트게임 기능 - data - 5.5h

### ISSUE THREAD

**Issue by nosorae** [f-lab-edu/chart-trainer#3]
## What users can do with this feature
 - 유저는 실제 데이터로 차트게임을 할 수 있다.

## Todo
- [x] DataSource 구현 (4h)
  - [x] Retrofit 셋업 (1h)
  - [x] Network 로부터 새로운 차트 정보 Get (중복검사는 UseCase 에서) (1h) -> **테스트까지 2시간 이상 걸림**
  - [x] Room database 셋업 (1h)
  - [x] DB 로부터 게임 히스토리 Dao 작성 (0.5h)
  - [x] DB 로부터 게임 히스토리 Dao 작성 (0.5h)
  - [x] DB 로부터 트레이드 히스토리 Dao 작성 (0.5h)
  - [x] Datastore Preference 셋업 get, set 작성 (1h)
- [x] Repository interface 구현 (1h)
