### ISSUE TITLE
[CT-30] 차트게임 기능 - domain/data 레이어 버그 수정

### ISSUE THREAD

**Issue by nosorae** [f-lab-edu/chart-trainer#30]
# TODO
- [x] 간헐적으로 Api응답으로 Tick 리스트가 null 로 오는 경우 파싱 에러 발생하여 nullable 처리
- [x] DB에 ChartEntity, TickEntity를 넣는 과정이 누락되어 DB에서 가져올 때 없는 Chart데이터, 빈 Tick 리스트가 나오는 문제가 있어서, Network에서 차트 데이터 받아오면 DB에 insert 하는 코드 추가
- [x] Api 쿼리 스트링에 날짜 범위를 시작 날짜와 끝날짜를 반대로 전달하여 400응답 내려오는 문제 수정
