### ISSUE TITLE
[CT-49] 잔잔바리 TODO

### ISSUE THREAD

**Issue by nosorae** [f-lab-edu/chart-trainer#49]
- [x] onUserAction을 UI 모델에서 분리  (ViewModel 테스트 과정에서 수정됨)
- [x] 두 개의 UseCase를 하나의 UseCase에 사용한 케이스를 수정 (SubscribeHomeDataUseCase) (ViewModel 테스트 과정에서 수정됨)
- [ ] [Chart 를 Memory Caching](https://github.com/f-lab-edu/chart-trainer/pull/60#discussion_r1649597590)
- [ ] nit; 인덴트가 많아지지 않도록 runTest는 위로 붙이는게 가독성에 더 좋을 것 같습니다. ([리뷰](https://github.com/f-lab-edu/chart-trainer/pull/64#discussion_r1661050239))
