### ISSUE TITLE
[CT-5] 홈화면 - 유저(익명)정보/설정정보를 확인/수정 하는 기능 - 8.5h

### ISSUE THREAD

**Issue by nosorae** [f-lab-edu/chart-trainer#5]
## What users can do with this feature
 - 유저는 유저 정보 화면에서 아래 정보들을 확인할 수 있다.
   - (임시로 정해진) 닉네임 
   - 총 자산 금액
   - 평균 수익률
   - 전적
   - 승률
   - 수수료
   - 총 게임 턴수
   - 차트 봉의 단위
- 유저는 유저 정보 화면에서 아래 정보들을 수정할 수 있다.
  -  수수료 설정
  - 총 게임 턴수 설정
  - 차트의 봉 단위 설정

## Todo
- [x] User 엔티티 설계 (0.5h)
- [x] 필요한 UseCase 들 추가 (0.5h)
- [x] UserRepository, SettingRepository interface 설계 (0.5h)
- [x] RepositoryImpl 구현 (1h)
- [x] 유저 정보 화면 UI/UX 개발 (3h)
- [x] 실행 테스트 및 수정 반복 (2h)

## Reference materials
- 알파스퀘어 차트게임 탭 UIUX

## TBD
- 닉네임과 프로필 사진은 로그인 기능과 함께 추가
