### ISSUE TITLE
[CT-6-1] 트레이드 내역 확인 기능 - 5h

### ISSUE THREAD

**Issue by nosorae** [f-lab-edu/chart-trainer#6]
## What users can do with this feature
- 유저는 하나의 게임에서 일어난 트레이드 내역을 (게임 종료 여부과 관계없이) 확인할 수 있다.
- 유저는 트레이드 내역으로 해당 트레이드가 발생한 턴/매수가격/매도가격/수수료 및 세금/체결금액/실현손익을 확인할 수 있다.
- 유저는 종료되지 않은 게임을 재개할 수 있다.

## Todo
- [x] SubscribeTradeHistoryUseCase 작성 및 필요한 Repository ineterface 작성 (1h)
- [x] Repository interface 를 구현 및 구현하기 위한 DataSource 구현 (1h)
- [x] ViewModel 구현 (1h)
- [x] UI 컴포넌트 제작/배치 및 ViewModel과 연결 (2h)
  - TopAppBar
    - 뒤로가기 아이콘 버튼
    - 타이틀 "매매 내역" 텍스트
  - 자산 변화 레이아웃 (게임 종료시에만 나옴)
    - 초기 자산 텍스트
    - 화살표 아이콘 텍스트
    - 총 평가 자산 텍스트
    - 수익 텍스트
  - 리스트
    - 해당턴/총턴 구분 텍스트
    - 매매내역 리스트 아이템 (턴/매수가격/매도가격/수수료 및 세금/체결금액/실현손익 정보 텍스트)

## Reference materials
- 알파스퀘어 차트게임
