### ISSUE TITLE
[CT-7] 게임 내역 확인 기능 - 4h

### ISSUE THREAD

**Issue by nosorae** [f-lab-edu/chart-trainer#7]
## What users can do with this feature
 - 유저는 이때까지 진행한 게임을 리스트 형태로 확인할 수 있다.
 - 각 게임마다 종료여부/기업 아이콘/이름/수익률/수익을 확인할 수 있다.
 - 게임 정보에 대해 더 자세하게 확인하기 위해 "게임 트레이드 내역 화면"으로 이동할 수 있다.

## Todo
- [x] Entity 작성 (이미 작성되어있을 것임. 누락이나 불필요한 게 없는지 확인정도만)
- [x] SubscribeGameHistoryUseCase 작성 및 필요한 Repository interface 작성 (1h)
- [x] Repository interface 구현 및 구현하기 위한 DataSource 구현 (1h) 
- [x] ViewModel 구현 (1h)
- [x] UI 컴포넌트 제작/배치 및 ViewModel과 연결 (1h)
  - TopAppBar
    - 타이틀
  - 리스트
    - 게임 내역 리스트 아이템 (기업 아이콘 이미지, 기업 이름, 수익률/수익, 더보기 아이콘)

## Reference materials
- 알파스퀘어 차트게임
