### ISSUE TITLE
[CT-8] README 작성 - 11h (+ 버퍼 5h)

### ISSUE THREAD

**Issue by nosorae** [f-lab-edu/chart-trainer#8]
## Todo
- [ ] 앱 간단 소개 (0.5h)
- [ ] 아키텍처 시각화하여 첨부 (이번 기회에 시각화 툴 익히며 - 3h)
- [ ] 화면 네비게이션 시각화하여 첨부 (0.5h)
- [ ] gif로 스크린 샷 첨부 (0.5h)
- [ ] 브랜치 전략 시각화하여 첨부 (0.5h)
- [ ] **문제/어려웠던 점과 해결과정과 이유 간략히 소개 + (길어진 경우 블로그 포스팅 후 링크 첨부)** (5h + 버퍼 5h)
- [ ] 유명 레포지토리 레퍼런스 5 개 참고하고 필요할지 판단하여 추가 (1h)
